# Generated by Django 3.2.7 on 2021-09-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default='room', max_length=100),
        ),
    ]
